version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service-container
    ports:
      - "3003:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/productManagement

volumes:
  mongo-data:
